### ISSUE TITLE
Out of Bounds Exception

### ISSUE THREAD

**Issue by omnitree** [Team-MoXie/InventoryManager#22]
![image](https://user-images.githubusercontent.com/33238905/94980129-22554400-04e4-11eb-9dd4-c97b70addf4f.png)

I sent an email that had the date and email address and got this error that kept on repeating until I went and deleted the email I had sent. 

(originally from Arturo on CustomerOrders Repo)

**Comment by ArturoVal** [comment]
Didn't look like this was a problem in the last demo day. Will create a new issue if it pops up again.
